In [ ]:
print("heklo ")

heklo 


In [ ]:
import re
text="python is very esay my number is 6358274851 my mai is murali@gmail.com"
re.search("python",text).group()
re.match("python",text).group()
re.findall("a",text)
re.findall(r"\d+",text)
re.findall(r"\S+@\S+",text)
re.split(r"\s+",text)



['python',
 'is',
 'very',
 'esay',
 'my',
 'number',
 'is',
 '6358274851',
 'my',
 'mai',
 'is',
 'murali@gmail.com']

In [3]:
import numpy as np
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.zeros(5)
np.zeros((3,4))
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)

(2, 3)
2
6
int64
8
48


In [5]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[1:4]
print(arr1[:3])

[1 2 3]


In [23]:
arr=np.array([[1,2],[4,5]])
arr[1:3,1:3]

array([[5]])

In [24]:
arr=np.array([[1,2,3],[4,5,6]])
arr.reshape(2,3)
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

21
3.5
1.707825127659933
2.9166666666666665


In [34]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(arr)
values,vectors=np.linalg.eig(arr)

values
vectors
print(arr.reshape(9,-1))
print(arr.flatten())

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[1 2 3 4 5 6 7 8 9]
