In [2]:
# NumPy Tutorial for AI/ML
# This notebook introduces core NumPy concepts with examples, exercises, and solutions.

import numpy as np

# Display arrays in a readable way
np.set_printoptions(precision=3, suppress=True)


# NumPy Tutorial for AI/ML

This notebook introduces NumPy with clear examples, small exercises, and full solutions. It is designed for beginners who want to build a strong foundation for AI and machine learning.

## 1. Create Arrays from Python Lists

NumPy arrays can be created from Python lists using `np.array()`.

```python
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1)
print(arr2)
print(arr3)
```


In [3]:
# Create 1D, 2D, and 3D arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1)
print(arr2)
print(arr3)


[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 2. Array Attributes and Data Types

You can inspect an array using attributes such as shape, size, ndim, dtype, and itemsize.

```python
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)
```


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print("shape:", arr.shape)
print("size:", arr.size)
print("ndim:", arr.ndim)
print("dtype:", arr.dtype)
print("itemsize:", arr.itemsize)


shape: (2, 3)
size: 6
ndim: 2
dtype: float64
itemsize: 8


## 3. Indexing, Slicing, and Fancy Indexing

You can access elements using simple indexes, slices, boolean masks, and integer arrays.

```python
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[1:4])
print(arr[arr > 30])
```


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[1:4])
print(arr[arr > 30])

mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat[1, 2])
print(mat[:, 1])


10
[20 30 40]
[40 50]
6
[2 5]


## 4. Reshape, Resize, and Flatten Arrays

Use reshape(), ravel(), flatten(), transpose(), and expand_dims() to change array structure.

```python
arr = np.arange(1, 10)
print(arr.reshape(3, 3))
print(arr.ravel())
print(arr.reshape(1, -1).shape)
```


In [6]:
arr = np.arange(1, 10)
print(arr.reshape(3, 3))
print(arr.ravel())
print(arr.reshape(1, -1).shape)
print(arr.T if arr.ndim > 1 else arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
(1, 9)
[1 2 3 4 5 6 7 8 9]


## 5. Vectorized Operations and Broadcasting

NumPy performs elementwise operations efficiently and supports broadcasting across shapes.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * 2)
```


In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * 2)

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 0, 1])
print(x + y)


[5 7 9]
[2 4 6]
[[2 2 4]
 [5 5 7]]


## 6. Aggregation and Statistical Computations

NumPy provides fast functions for computing statistics over arrays.

```python
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
```


In [8]:
arr = np.array([1, 2, 3, 4, 5])
print("sum:", np.sum(arr))
print("mean:", np.mean(arr))
print("std:", np.std(arr))
print("min:", np.min(arr))
print("max:", np.max(arr))

sum: 15
mean: 3.0
std: 1.4142135623730951
min: 1
max: 5


## 7. Boolean Masking and Conditional Selection

Boolean masks help filter arrays based on conditions.

```python
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(mask)
print(arr[mask])
```


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(mask)
print(arr[mask])
print(arr[arr % 2 == 0])

[False False False  True  True  True]
[4 5 6]
[2 4 6]


## 8. Stacking, Splitting, and Concatenation

NumPy can combine arrays in several useful ways.

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b]))
print(np.vstack([a, b]))
```


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b]))
print(np.vstack([a, b]))
print(np.hstack([a, b]))
print(np.split(np.array([1, 2, 3, 4, 5, 6]), 3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


## 9. Random Numbers and Basic Distributions

NumPy can generate random values for simulations and sampling.

```python
rng = np.random.default_rng(42)
print(rng.integers(0, 10, size=5))
print(rng.random((2, 3)))
```


In [11]:
rng = np.random.default_rng(42)
print(rng.integers(0, 10, size=5))
print(rng.random((2, 3)))
print(rng.normal(loc=0.0, scale=1.0, size=5))

[0 7 6 4 4]
[[0.697 0.094 0.976]
 [0.761 0.786 0.128]]
[-0.853  0.879  0.778  0.066  1.127]


## 10. Exercises: NumPy Basics

Try these exercises on your own before looking at the solutions.

1. Create a 1D array of numbers from 1 to 10.
2. Create a 2D array with shape (2, 3) using a list of lists.
3. Print the shape, size, and dtype of the array.
4. Extract all values greater than 5 from an array.
5. Reshape a 1D array of 12 elements into shape (3, 4).
6. Compute the mean and sum of an array.


In [12]:
# Exercise space
# Try solving the questions above here before checking the solutions.

# Example placeholder
# arr = np.arange(1, 11)
# ...


## 11. Solutions: NumPy Basics

Here are complete solutions for the exercises.


In [13]:
# Solution 1
arr1 = np.arange(1, 11)
print(arr1)

# Solution 2
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Solution 3
print("shape:", arr2.shape)
print("size:", arr2.size)
print("dtype:", arr2.dtype)

# Solution 4
arr3 = np.array([1, 2, 3, 6, 8, 10])
print(arr3[arr3 > 5])

# Solution 5
arr4 = np.arange(1, 13)
arr4 = arr4.reshape(3, 4)
print(arr4)

# Solution 6
arr5 = np.array([2, 4, 6, 8, 10])
print("sum:", np.sum(arr5))
print("mean:", np.mean(arr5))

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
size: 6
dtype: int64
[ 6  8 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sum: 30
mean: 6.0
